### PR TITLE
Add a repository.bzl helper

### PR DESCRIPTION
**Pull request by achew22**
This helper can be used when creating repository rules.

### CODE REVIEW

**Comment by aiuto** [comment]
maybe is baked into bazel. The is no need for this PR.

load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")

**Comment by achew22** [comment]
Cool, thanks for the pointer. Do you know what the heuristic is for things being put in {sky,star}lib vs shipping in `@bazel_tools`?

**Comment by aiuto** [comment]
Closing the loop.  There is not much need for this, since maybe is baked into Bazel via @bazel_tools 
   load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")

@thomasvl  You are right. We should document @bazel_tools 
https://github.com/bazelbuild/bazel/issues/9460

**Comment by achew22** [comment]
Thanks for following up! Sounds correct to me

**Pull request closed without merging**
