### PR TITLE
Create CODEOWNERS

### PR DESCRIPTION
**Pull request by dslomov**
Adding GitHub repo admins as global CODEOWNERS

### CODE REVIEW

**Comment by dslomov** [comment]
@thomasvl @allevato do you still want to be GitHub repo admins?

**Comment by allevato** [comment]
I'm happy to be taken off the admin list now that @c-parsons is owning it. The more recent issues/PRs have needed review from someone more qualified on Bazel/Starlark than I am 🙂

**Comment by laurentlb** [comment]
You can add me instead.

**Comment by dslomov** [comment]
Updated - ptal

**Comment by thomasvl** [comment]
dslomov, did you mean for this to get merged?

**Comment by dslomov** [comment]
Indeed

**Comment by dslomov** [comment]
How do I merge? directly into GitHub?

**Comment by thomasvl** [comment]
> How do I merge? directly into GitHub?

Yup.

**Pull request merged**
