### PR TITLE
Remove unused, empty //rules:bins filegroup, allowing us to simplify distribution/BUILD

### PR DESCRIPTION
**Pull request by tetromino**
//rules:bins has not been used since 14f17ae7f71f347b5e720fca55e33df40bc4e5d5

Alternative to https://github.com/bazelbuild/bazel-skylib/pull/358

### CODE REVIEW

**Review by comius — APPROVED** [review]

**Comment by cafsenra** [comment]
@tetromino and @comius can you tell when will be a release with this fix? And which release will be?

**Comment by tetromino** [comment]
@cafsenra, we can make a point release for this. Is it breaking you because you turn on `--incompatible_disallow_empty_glob`?

**Comment by cafsenra** [comment]
@tetromino yes it is that. Thank you, a new release will be welcome ;)

**Comment by tetromino** [comment]
Released https://github.com/bazelbuild/bazel-skylib/releases/tag/1.2.1

**Pull request merged**
