### PR TITLE
initial checkin of skydoc skylark rule

### PR DESCRIPTION
**Pull request by c-parsons**

### CODE REVIEW

**Comment by laurentlb** [comment]
Why bazel-skylib and not https://github.com/bazelbuild/skydoc?

**Comment by c-parsons** [comment]
I suppose skydoc would be okay. Our cross-repo dependencies would then be:

skydoc -> bazel_skylib -> io_bazel
skydoc tests, in io_bazel -> skydoc -> bazel_skylib

**Comment by laurentlb** [comment]
Skydoc repository depends on both Skylib and Bazelbuild repositories.
This should be the same for the tests (unless I missed something?)

**Comment by thomasvl** [comment]
@c-parsons is this being dropped?

**Comment by c-parsons** [comment]
Yes, I'd like to drop this. I have taken the alternative approach of incorporating into the skydoc directory, which I'm waiting on approval for. https://github.com/bazelbuild/skydoc/pull/105
I was dragging my feet on dropping this in case my reviewers happened to change their mind, but I doubt they will 0:)

**Pull request closed without merging**
