### PR TITLE
Add --incompatible_remap_main_repo for test

### PR DESCRIPTION
**Pull request by meteorcloudy**
https://github.com/bazelbuild/bazel-skylib/issues/173

### CODE REVIEW

**Comment by meteorcloudy** [comment]
@c-parsons Can you help merge this PR?

**Comment by c-parsons** [comment]
ugh, we have to resolve the buildifier issues or remove it as a presubmit request (or worse, manually push)

I'll try to find some time today to push the fixes to this PR

**Comment by thomasvl** [comment]
#177 should clear things for the repo.

**Comment by aiuto** [comment]
I think #184 will eliminate the need to run with this flag.

**Comment by aiuto** [comment]
Is this obsolete?

**Comment by comius** [comment]
I believe this is obsolete.

**Pull request closed without merging**
