### PR TITLE
fix broken CI: clean up linter failures and remove now-breaking --incompatible_remap_main_repo

### PR DESCRIPTION
**Pull request by gregestren**

### CODE REVIEW

**Comment by gregestren** [comment]
This also has the [CI toolchain failures](https://buildkite.com/bazel/bazel-skylib/builds/550#5ddbcd81-2c46-4685-9c40-abee50ceb883):

```
ERROR: While resolving toolchains for target //tests:unittest_tests_test_0: no matching
toolchains found for types //toolchains/unittest:toolchain_type
```
It looks like this comes from including `--incompatible_remap_main_repo`. Is it safe to remove that flag from the CI now?

**Comment by c-parsons** [comment]
If all tests pass by removing that flag, that sounds fine. It was previously added to make tests pass -- if it's no longer required, great.

**Comment by gregestren** [comment]
Updated with build flag removal.

**Comment by c-parsons** [comment]
It looks like removal of that flag has broken more tests.

Let me know if you want some help investigating these failures...

**Comment by c-parsons** [comment]
FYI https://github.com/bazelbuild/bazel-skylib/issues/173

I'm rolling back the offending commit.

**Comment by gregestren** [comment]
Which broken tests were you referring to? The failures in this PR or from https://github.com/bazelbuild/bazel-skylib/issues/173?

**Comment by tetromino** [comment]
Is this pr still relevant? Lots of conflicts if you try to merge it.

**Comment by gregestren** [comment]
I've lost context on this. Let's revert. CI looks reasonable now anyway? https://buildkite.com/bazel/bazel-skylib

**Pull request closed without merging**
