### PR TITLE
Windows support for build_test

### PR DESCRIPTION
**Pull request by codeschlosser**
Create a portable `empty_test` rule that always succeeds.
Use that as the test portion fo `build_test`

### CODE REVIEW

**Comment by codefables** [comment]
@googlebot I signed it!

**Comment by codefables** [comment]
@googlebot I consent.

**Comment by aiuto** [comment]
@sdtwigg You might want to look at this too, WRT to the build test refactoring you did recently.

**Comment by codefables** [comment]
@juliexxia Does this need anything else more from my side?

**Comment by juliexxia** [comment]
Apologies for the delay! Adding @meteorcloudy for windows domain knowledge. I think he's OOO until thursday though.

**Comment by codefables** [comment]
@googlebot I consent.

**Comment by aiuto** [comment]
Everyone seems to like this. Can we sort out the CLA part? This sometimes happens if different users push to the same PR. For example, from a corporate account and a personal account.

**Comment by FaBrand** [comment]
@codeschlosser You could try to close this PR and create a new one with a squashed branch. Since you probably have consented already this could work. I would also be happy to have this in skylib 👍

**Comment by codeschlosser** [comment]
@FaBrand, done #302

**Pull request closed without merging**
