### PR TITLE
Gazelle now handles imports from `@bazel_tools`

### PR DESCRIPTION
**Pull request by achew22**
`@bazel_tools` is tricky since it is effectively a part of the standard
library that can not have a `bzl_library` attached to it. As a simple
fix for this, `bzl_library` can have a srcs dependency on it so that it
includes the transitive closure of all of its dependencies.

`@bazel_tools` imports are rewritten into the `srcs` attribute since
they are `exports_files`ed from the @bazel_tools.

### CODE REVIEW

**Comment by achew22** [comment]
@segiddins I believe this addresses one of your manual changes. Could I have you give it a once over to verify it does.

@jayconrod could I have you take a look at this? Thanks so much!

**Comment by achew22** [comment]
I've figured out how to satisfy buildifier's vengeful constraints and all the tests are green now and ready for review. Sorry about that!

**Comment by segiddins** [comment]
@achew22 I was adding the `.bzl` source file into `deps` rather than `srcs`

**Review by jayconrod — APPROVED** [review]

**Comment by jayconrod** [comment]
LGTM, but I don't have mergeability.

**Comment by achew22** [comment]
@segiddins PTAL

**Review by segiddins — APPROVED** [review]

**Comment by achew22** [comment]
@jayconrod could I have you poke this one more time. I think (hope?) that your approval is now sufficient.

**Review by jayconrod — APPROVED** [review]

**Comment by jayconrod** [comment]
Approved, but I still can't merge anything in this repo.

**Comment by achew22** [comment]
☹️ @c-parsons do you have any ideas on why Jay's approval isn't working? I hate to keep coming back to you to review stuff but I don't know how to fix this one

**Comment by achew22** [comment]
@c-parsons friendly ping on this

**Review by c-parsons — APPROVED** [review]

**Comment by c-parsons** [comment]
Hmm, I'm not sure why Jay's approval still isn't working. :(
Regardless, have my approval.

**Pull request merged**
