### PR TITLE
Add helper functions for module extensions as `modules`

### PR DESCRIPTION
**Pull request by fmeum**
Adds a new module `modules` with two helper functions for module extensions:

* `use_all_repos` makes it easy to return an appropriate `extension_metadata` from a module extension (if supported) to indicate that all repositories generated by the extension should be imported via `use_repo`.
* `as_extension` turns a WORKSPACE macro into a module extension that uses `use_all_repos` to automate the generation of `use_repo` calls.

### CODE REVIEW

**Comment by fmeum** [comment]
@Wyverald Could you review this from the Bzlmod dev perspective?
@tetromino Could you review this from the Bzlmod user perspective?

I can also add full e2e tests if desired.

**Comment by fmeum** [comment]
@Wyverald Friendly ping

**Comment by fmeum** [comment]
CI is failing due to the missing Python toolchain registration.

**Review by Wyverald — APPROVED** [review]

**Comment by fmeum** [comment]
@Wyverald Tests are passing now.

**Comment by fmeum** [comment]
@Wyverald Friendly ping

**Comment by fmeum** [comment]
After the release of 7.1.0, I will add `reproducible`.

**Review by tetromino — APPROVED** [review]
LGTM. Sorry for the wait!

**Pull request merged**
