### PR TITLE
e2e tests: make them run on Windows

### PR DESCRIPTION
**Pull request by laszlocsomor**

### CODE REVIEW

**Comment by laszlocsomor** [comment]
I'm puzzled by the Buildifier job failure, it works locally:
```
  $ ~/buildtools-releases/0.22.0/buildifier --lint=warn tests/BUILD ; echo $?
0
```

I couldn't run the docker image locally so I can't repro the failure:

```
  $ docker run -it --rm --init -v $PWD:/workdir --workdir /workdir gcr.io/bazel-untrusted/buildifier
+++ :female-detective: Looking for WORKSPACE, BUILD, BUILD.bazel and *.bzl files
+++ :bazel: Running buildifier (format check)
--- :hammer_and_wrench: Printing raw output for debugging
##### :bazel: buildifier: error while checking format:
<pre><code></code></pre>
+++ :buildkite: Uploading output via 'buildkite annotate'
Traceback (most recent call last):
  File "/usr/local/bin/buildifier.py", line 163, in <module>
    sys.exit(main())
  File "/usr/local/bin/buildifier.py", line 106, in main
    upload_output(output)
  File "/usr/local/bin/buildifier.py", line 36, in upload_output
    input=output.encode(locale.getpreferredencoding(False)),
  File "/usr/local/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'buildkite-agent': 'buildkite-agent'
```

**Comment by c-parsons** [comment]
Buildifier failures fixed at HEAD!
Proceeding to review...

**Comment by laszlocsomor** [comment]
Thank you. I don't know how to add this to CI. /cc @meteorcloudy.

I have no right to merge this. @laurentlb , while @c-parsons is away, could you please merge this PR for me? Since I plan to contribute more to Skylib, would it make sense to grant me merge rights?

**Comment by meteorcloudy** [comment]
@laszlocsomor To add them to CI, you should remove the following lines here:
https://github.com/bazelbuild/bazel-skylib/blob/b2b4471332abdbf8979c89ca5e2cbb4f3a2bdc0f/.bazelci/presubmit.yml#L53-L55

**Comment by c-parsons** [comment]
@laszlocsomor you should have merge rights now.

**Comment by laszlocsomor** [comment]
Thank you Chris! \o/

**Comment by laszlocsomor** [comment]
Suspected error: https://github.com/bazelbuild/bazel/issues/7761

**Comment by laszlocsomor** [comment]
CI logs (from https://buildkite.com/bazel/bazel-skylib/builds/375#3fd7cdbb-0ae6-49ff-8703-ad8cbb382d95):
```
ℹ️ Environment Variables | 0s
...
  | LOCALAPPDATA=(C:\Windows\system32\config\systemprofile\AppData\Local)
...

Test (unreleased binary) | 7s
...
  | bazel --output_user_root=D:/b test [...] --test_env=LocalAppData --test_env=USE_BAZEL_VERSION -- //...
```

Test log:
```
2019/03/19 08:12:23 could not get the user's cache directory: %LocalAppData% is not defined
```

**Comment by laszlocsomor** [comment]
@meteorcloudy : Could you please review https://github.com/bazelbuild/bazel-skylib/pull/121/commits/dc2d5cb065e67b3fd08e886be54a90476ea059ca ?

**Comment by meteorcloudy** [comment]
Turned out the error message was from Bazelisk:
https://github.com/philwo/bazelisk/blob/81b696d64c2943c345cb0d902c94279715fc0b01/bazelisk.py#L243

**Comment by laszlocsomor** [comment]
Actually, from here: https://github.com/philwo/bazelisk/blob/de217bc912a2558e3e22839e63e8cac4565f573f/bazelisk.go#L462

The outer Bazel is Bazelisk, running HEAD Bazel. It passes `--test_env=LocalAppData` but only `LOCALAPPDATA` is defined (https://github.com/bazelbuild/bazel/issues/7761).

The inner Bazel (in the shell test) is `/c/bazel/bazel` (also Bazelisk, running the same HEAD Bazel), giving the above error.

**Pull request merged**
