### PR TITLE
Update maintainer guide for bzlmod and bazel-central-registry

### PR DESCRIPTION
**Pull request by tetromino**

### CODE REVIEW

**Review by brandjon — APPROVED** [review]
That's an intimidating series of steps at a glance, but I guess it can't be helped.

No need to do it in this PR, but it might be nice to separate the release notes template into a separate file. I had trouble initially visually parsing the template vs the surrounding instructions.

**Comment by tetromino** [comment]
As a followup, instead of a long set of instructions, we ought to have (1) a script, and (2) a hook that automatically runs said script after a release is tagged on github. But that's for future maintainers :)

**Comment by fmeum** [comment]
You could use https://github.com/bazel-contrib/publish-to-bcr to automate BCR releases. Many rulesets are already using it.

**Comment by tetromino** [comment]
@fmeum - nice, thank you for the suggestion!

**Comment by tetromino** [comment]
... alas, it seems that publish-to-bcr assumes a 1-1 mapping between git repo and module. Won't work for us since gazelle plugin is a separate module.

**Comment by tetromino** [comment]
https://github.com/bazel-contrib/publish-to-bcr/issues/46

**Pull request merged**
