### PR TITLE
CI updates.

### PR DESCRIPTION
**Pull request by thomasvl**
- Retire the use of travis for testing.
- Update buildkite config:
  - Enable buildifier testing (close to what was on travis, and is being improved.)
  - Update the config to now test the latests release and the latest green, replacing
    the "head" testing on travis.

### CODE REVIEW

**Comment by thomasvl** [comment]
@fweikert fyi

**Comment by fweikert** [comment]
Note: with this PR you'll lose the buildifier format check (until https://github.com/bazelbuild/continuous-integration/issues/506 is solved).

**Comment by thomasvl** [comment]
@laurentlb @c-parsons do you want to keep travis just for the more complete buildifier for the time being?

**Comment by c-parsons** [comment]
Lets proceed with this change anyway. We can do manual buildifier formatter checks periodically (and try to ensure they are done for PRs) in the interim.

**Pull request merged**
