### PR TITLE
Allow unit test rules to be documented

### PR DESCRIPTION
**Pull request by UebelAndre**
I find it more ergonomic to add notes or a description about a test to a `doc` attribute, similar to other rules, vs a comment block above it or in the `impl` function docstring. Hopefully this can improve the readability of test rules.

### CODE REVIEW

**Comment by UebelAndre** [comment]
@tetromino Friendly ping 😅

**Comment by UebelAndre** [comment]
@tetromino One more friendly ping 😄 It'd be nice to have this in the next release

**Review by tetromino — APPROVED** [review]
Seems reasonable. Sorry for overlooking the PR!

**Comment by tetromino** [comment]
On second thought - we made a mistake here. New parameter should go to the end of the list, otherwise we break users who use `analysistes.make` with positional parameters and expect parameter 2 to be the `expect_failure` bool. Quick fix PR incoming, please review.

**Pull request merged**
