### PR TITLE
Remove --experimental_build_setting_api usage

### PR DESCRIPTION
**Pull request by juliexxia**
Deprecating this flag so removing all usage.

### CODE REVIEW

**Comment by juliexxia** [comment]
Hm, "rules/common_settings.bzl:91:18: parameter 'build_setting' is experimental and thus unavailable with the current flags. It may be enabled by setting --experimental_build_setting_api" even though --experimental_build_setting_api is set to true by default (and has been for some while)

**Comment by aiuto** [comment]
I have to say I am baffled. You are removing the flag, and yet the stuff
complains about using it.
How about a CL which just does tests/common_settings_test.sh alone.
If that works, then cut it from the rule in a second pass.

**Comment by aiuto** [comment]
any luck with the tests?

**Comment by juliexxia** [comment]
Yep, but now getting a bunch of buildifer errors from unrelated tests...investigating...

**Comment by jin** [comment]
The buildifier failures started happening after the CI started to use Buildifier 3.0.0, from 2.2.1

At commit 560d7b2:

2.2.1, buildifier passes: https://buildkite.com/bazel/bazel-skylib/builds/986#b171ed75-253b-4e14-8e0e-47d84c5ca20a
3.0.0, buildifier fails: https://buildkite.com/bazel/bazel-skylib/builds/988#0617d4b5-65e4-4c78-bc3f-3b7b7da8d5d2

**Comment by juliexxia** [comment]
Yeah I realized that as well - @vladmos did you ever get a chance to take a look at these failures?

**Comment by vladmos** [comment]
There were newly discovered bugs in the version of buildifier I wanted to release last week, I'll make a new release that will make most of the findings disappear early next week. The rest of the warnings can be temporarily disabled by special comments to unblock pull requests.

**Comment by juliexxia** [comment]
Looks like buildifer issues got fixed thanks @vladmos !

Could a reviewer take a look now? Thanks!

**Pull request merged**
