### PR TITLE
Add write_file and copy_file docs to README

### PR DESCRIPTION
**Pull request by cpsauer**
I'd run across write_file from a Google search, and noticed, while using it, that its docs weren't in the README. 
So I figured I'd toss up a quick PR to add it and it's cousin, copy_file.
The README's list still isn't complete, but it's at least more complete.

### CODE REVIEW

**Review by tetromino — CHANGES_REQUESTED** [review]
Nit: use alphabetical order, please

**Comment by cpsauer** [comment]
@tetromino derp, sorry about that. Done.

**Review by tetromino — APPROVED** [review]
Thanks!

**Comment by cpsauer** [comment]
Thank you :)

**Pull request merged**
