### PR TITLE
Update changelog for release 1.1.0

### LINKED ISSUE #316: Request for Release
Would it be possible to get a new release of `bazel_skylib`?

### PR DESCRIPTION
**Pull request by tetromino**
Fixes #316.

### CODE REVIEW

**Comment by tetromino** [comment]
... actually, I'd like to hold off on this and merge a couple of PRs first.

**Comment by tetromino** [comment]
PRs merged - now, we're in a good state for 1.1.0

**Comment by FaBrand** [comment]
@tetromino could you consider including #301, or are there reasons to not have it?

**Comment by tetromino** [comment]
@FaBrand - the only reason is limited reviewer bandwidth at the moment

**Pull request merged**
